const PREFIX = "http://localhost:8081"
export const GET_DEVICE_INFO = PREFIX + "/device/info"
export const SCREEN_CAPTURE = PREFIX + "/media/screenCapture"
export const MEDIA_LIST = PREFIX + "/media/list"
export const MEDIA_CLEAN = PREFIX + "/media/clean"
export const START_SCREEN_RECORDING = PREFIX + "/media/startScreenRecording"
export const STOP_SCREEN_RECORDING = PREFIX + "/media/stopScreenRecording"
export const RETROFIT_INFO = PREFIX + "/retrofit/info"
export const RETROFIT_EDIT = PREFIX + "/retrofit/edit"

export const WEB_SOCKET_DEVICE = "/device"
export const WEB_SOCKET_LOGCAT = "/logcat"
export const WEB_SOCKET_NET = "/logcat/net"
export const WEB_SOCKET_MEDIA_ADD = "/media/add"